export const projects = [
    {
        technologies: [],
        _id: "ABC123",
        title: "IoT",
        image: "IoT Image",
        description: "Course IoT",
        link: "IoT Link",
    },
    {
        technologies: [],
        _id: "ABC123",
        title: "IoT",
        image: "IoT Image",
        description: "Course IoT",
        link: "IoT Link",
    },
    {
        technologies: [],
        _id: "ABC123",
        title: "IoT",
        image: "IoT Image",
        description: "Course IoT",
        link: "IoT Link",
    },
    {
        technologies: [],
        _id: "ABC123",
        title: "IoT",
        image: "IoT Image",
        description: "Course IoT",
        link: "IoT Link",
    },
    {
        technologies: [],
        _id: "ABC123",
        title: "IoT",
        image: "IoT Image",
        description: "Course IoT",
        link: "IoT Link",
    },
    {
        technologies: [],
        _id: "ABC123",
        title: "IoT",
        image: "IoT Image",
        description: "Course IoT",
        link: "IoT Link",
    },
    {
        technologies: [],
        _id: "ABC123",
        title: "IoT",
        image: "IoT Image",
        description: "Course IoT",
        link: "IoT Link",
    },

]